### ISSUE TITLE
figure8.shex: Constraints on Event's :start and :end seems wrong.

### ISSUE THREAD

**Issue by lschmelzeisen** [knowledge-graphs-tutorial/examples#2]
Figure 8 of the paper (section 2.3.1) depicts the following shape diagram:

![shapes-uml](https://user-images.githubusercontent.com/488697/100909629-42e25000-34cd-11eb-8461-7d366243c5c2.png)

That is, for the `Event` shape exactly one `start` and `end` time should be present.

However, the example currently only specifies these properties as optional.

https://github.com/knowledge-graphs-tutorial/examples/blob/37cc7fda85450d9caec87a946acac98d46e74b5b/Section2/2_3_1_Shapes_graphs/figure8.shex#L13-L14

Since I'm not well-versed in ShEx I can't make this change myself, but it would be nice if someone could take a look at it.

**Comment by labra** [comment]
Ops, you are right!, I will change that, thanks 👍

**Comment by lschmelzeisen** [comment]
Seems to have been addressed by 16b74d97482961be8c5adc87043a629526f6cada.
